# Dispatcher configuration file.
# Save this file as /etc/scion/dispatcher.toml

[log.console]
# Console logging level (debug|info|error) (default info)
level = "info"

[dispatcher]
id = "dispatcher"

# File permissions of the ApplicationSocket socket file, in octal. (default "0770")
socket_file_mode = "0770"
