# SCION Daemon configuration file
# Save this file as /etc/scion/sd.toml

[general]
id = "sd"
config_dir = "/etc/scion"
reconnect_to_dispatcher = true

[trust_db]
connection = "/var/lib/scion/sd.trust.db"

[path_db]
connection = "/var/lib/scion/sd.path.db"
